### ISSUE TITLE
doesn't load board data

### ISSUE THREAD

**Issue by trenkert** [swordbeta/trello-burndown#10]
although it does find the board ID, board name and card data aren't found. the chart remains empty.

**Comment by mtricht** [comment]
Hey, gonna need slightly more information here.
Are you seeing any errors in the logs?
What do your card titles look like?

**Comment by trenkert** [comment]
logs

```
"GET / HTTP/1.1" 200 1561
::1 - - [10/May/2018:20:10:36 +0200] "GET /add HTTP/1.1" 200 1369
::1 - - [10/May/2018:20:11:04 +0200] "POST /add HTTP/1.1" 302 0
::1 - - [10/May/2018:20:11:05 +0200] "GET /index HTTP/1.1" 200 1561
::1 - - [10/May/2018:20:11:53 +0200] "GET /view/fTYzcBm0 HTTP/1.1" 200 3003

```

card titles: 

`(12) edit structure
`

![image](https://user-images.githubusercontent.com/143727/39889308-d11801b2-5497-11e8-89d5-a2720a27cfd7.png)


![image](https://user-images.githubusercontent.com/143727/39889338-e283a0fa-5497-11e8-9bf2-56dc8c1d03da.png)

**Comment by mtricht** [comment]
Okay, as you don't have the board name, can you check the following:

1. Is your api key and user token correctly in the `config.yaml`? If you compiled yourself, is the config in the same directory as the binary? If using docker, is the config properly mounted?
2. Can you check that the board ID is indeed `fTYzcBm0`?

**Comment by trenkert** [comment]
I used the binary, the config.yaml is in the same folder. api key and token are correct (I triple-checked). Board ID is correct as well

**Comment by mtricht** [comment]
Can you set `debug: true` in the config, restart the server and refresh the board with the refresh button?
You should see something like in the logs if it's successful:

```
2018/05/10 22:07:18 watcher.go:85: Checking board ID #BSFpPCq6
2018/05/10 22:07:37 watcher.go:96: Board name: Sprint #126 | 24 April - 7 May
2018/05/10 22:07:39 watcher.go:124: Cards progress: 37/48
2018/05/10 22:07:39 watcher.go:125: Total points: 15.500000/27.000000
```

**Comment by trenkert** [comment]
I get an error message

```
2018/05/10 22:48:11 server.go:13: Listening on http://127.0.0.1:8087
::1 - - [10/May/2018:22:48:41 +0200] "GET / HTTP/1.1" 200 1561
2018/05/10 22:48:58 watcher.go:85: Checking board ID #fTYzcBm0
2018/05/10 22:48:58 watcher.go:85: Checking board ID #fTYzcBm0
2018/05/10 22:48:59 watcher.go:88: Error: json: cannot unmarshal number 32767.5 into Go struct field list.pos of type int
::1 - - [10/May/2018:22:48:58 +0200] "GET /refresh/fTYzcBm0 HTTP/1.1" 302 50
2018/05/10 22:48:59 watcher.go:88: Error: json: cannot unmarshal number 32767.5 into Go struct field list.pos of type int
::1 - - [10/May/2018:22:48:58 +0200] "GET /refresh/fTYzcBm0 HTTP/1.1" 302 50
::1 - - [10/May/2018:22:48:59 +0200] "GET /index HTTP/1.1" 200 1561
::1 - - [10/May/2018:22:49:01 +0200] "GET /view/fTYzcBm0 HTTP/1.1" 200 3003

```

**Comment by mtricht** [comment]
I see, I'll work on an update and let you know when that's fixed!

**Comment by mtricht** [comment]
@trenkert Just released v1.7.0 but can't reproduce a list that is on position 32767.5; can you verify on your end that it works?

**Comment by trenkert** [comment]
it's working now, thanks a lot!

**Comment by renatopanda** [comment]
Hey, I'm getting this bug again in one of my boards using the latest docker image

`2019/04/18 15:51:14 watcher.go:88: Error: json: cannot unmarshal number 32767.5  into Go struct field list.pos of type int`

I did a simple test using the trello sandbox to request the lists of my board and noticed that the 32767.5 value is found at the "pos" element, which is not an int.
```
[
  {
    "id": "5cb863a912f5264c6xxxxxxx",
    "name": "STORIES",
    "closed": false,
    "idBoard": "5c76a242fbdb44092xxxxxx",
    "pos": 32767.5,
    "subscribed": false,
    "softLimit": null
  },
```

Cheers!

**Comment by mtricht** [comment]
@renatopanda That's a pretty old build, the file `watcher.go` doesn't exist anymore. Can you try a more recent version?

**Comment by renatopanda** [comment]
@mtricht thanks! I was using the latest docker image/tag which for some reason imported 1.7.0, the newer one (1.8.0) fixes the issue. :+1:
