### ISSUE TITLE
Add basic auth to add/remove actions

### ISSUE THREAD

**Issue by renatopanda** [swordbeta/trello-burndown#12]
Would it be possible to add a very basic auth (maybe using config.yml vars) just to avoid certain people to use those two actions by mistake? The goal is just to use it in a learning/class environment with students.

Thanks!

**Comment by mtricht** [comment]
Added a `http.readOnly` config for this ;) Very cool that you're using this!

The config is now also watched, so you can change this without having to restart anything.
